/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agent-support/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_agent_support_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_agent_support_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-support/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_agent_support_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-support/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_agent_support_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-support/runs/{run_id}/confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Confirmation */
        post: operations["resolve_confirmation_api_agent_support_runs__run_id__confirmations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-support/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_agent_support_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionOutcome */
        ActionOutcome: {
            /** Action Id */
            action_id: string;
            /** Backend */
            backend: string;
            /** Message */
            message: string;
            /** Success */
            success: boolean;
        };
        /** ActionRequest */
        ActionRequest: {
            /** Action Id */
            action_id?: string | null;
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "create_ticket" | "send_reply" | "escalate_to_human";
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /**
             * Requires Confirmation
             * @default true
             */
            requires_confirmation: boolean;
        };
        /** ConfirmationRequest */
        ConfirmationRequest: {
            action?: components["schemas"]["ActionRequest"] | null;
            /** Action Hash */
            action_hash: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject" | "modify";
            /** Version */
            version: number;
        };
        /**
         * ExecutionState
         * @enum {string}
         */
        ExecutionState: "queued" | "planning" | "executing" | "verifying" | "gating" | "web_verifying" | "no_info_check" | "pending_confirmation" | "action_executing" | "completed" | "escalated" | "cancelled" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PendingConfirmation */
        PendingConfirmation: {
            action: components["schemas"]["ActionRequest"];
            /** Action Hash */
            action_hash: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** RunRecord */
        RunRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Error */
            error?: string | null;
            pending_confirmation?: components["schemas"]["PendingConfirmation"] | null;
            request: components["schemas"]["RunRequest"];
            result?: components["schemas"]["SupportResult"] | null;
            /** Run Id */
            run_id: string;
            /** @default queued */
            state: components["schemas"]["ExecutionState"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Do Action
             * @default true
             */
            do_action: boolean;
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /** Identity */
            identity?: {
                [key: string]: string;
            } | null;
            /** Query */
            query: string;
            /**
             * Use Web
             * @default true
             */
            use_web: boolean;
            /** Vertical */
            vertical?: ("gov" | "saas" | "ec") | null;
        };
        /** SupportResult */
        SupportResult: {
            action?: components["schemas"]["ActionRequest"] | null;
            action_outcome?: components["schemas"]["ActionOutcome"] | null;
            /** Action Result */
            action_result?: string | null;
            /** Answer */
            answer?: string | null;
            /** Citations */
            citations?: string[];
            /**
             * Contradiction
             * @default false
             */
            contradiction: boolean;
            /**
             * Decision
             * @default escalate
             * @enum {string}
             */
            decision: "answer" | "escalate";
            /**
             * Forced Escalate
             * @default false
             */
            forced_escalate: boolean;
            /**
             * Groundedness
             * @default 0
             */
            groundedness: number;
            /**
             * Groundedness Decided
             * @default 0
             */
            groundedness_decided: number;
            /**
             * Identity Checked
             * @default false
             */
            identity_checked: boolean;
            /** Intent */
            intent?: ("question" | "request" | "incident") | null;
            /**
             * No Info Detected
             * @default false
             */
            no_info_detected: boolean;
            /**
             * Overall Confidence
             * @default 0
             */
            overall_confidence: number;
            /** Source Agreement */
            source_agreement?: number | null;
            /**
             * Used Web
             * @default false
             */
            used_web: boolean;
            /** Vertical */
            vertical?: string | null;
            /**
             * Warning
             * @default false
             */
            warning: boolean;
            /**
             * Web Reused
             * @default false
             */
            web_reused: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_agent_support_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"][];
                };
            };
        };
    };
    create_run_api_agent_support_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_agent_support_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_agent_support_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_confirmation_api_agent_support_runs__run_id__confirmations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_agent_support_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: number;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
